### PR TITLE
Added iotdb-2.0 module; rolled back iotdb-1.3 module

### PR DESCRIPTION
**Pull request by YangYumings**
## Added iotdb-2.0 module
1. Copy the file of the iotdb-1.3 module and rename it to iotdb-2.0;
2. Change iotdb-version to 2.0.0-SNAPSHOT;
3. Change all 1.3 to 2.0;

## rolled back iotdb-1.3 module to 'd820b0018f36263e001dc6715f89d72f5b636d6b'.
1. Delete all files under cn.edu.tsinghua.iot.benchmark.iotdb130 of the module iotdb-1.3;
2. Compare with the last commit of the master branch and restore the files of iotdb-1.3;
3. Prepare for Java reflection. Modify the following files:
3.1 Constants.java
3.2 DBSwitch.java
3.3 DBFactory.java
3.4 DBVersion.java
4. Delete the parameter is all nodes visible;

### CODE REVIEW

**Review by liyuheng55555 — APPROVED** [review]
LGTM. 请在根pom添加iotdb-2.0，然后确认现在所有包都还能成功构建 (`通过mvn clean package -am -DskipTests`)

**Comment by YangYumings** [comment]
编译与打包正常。
image

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM

**Comment by YangYumings** [comment]
Thanks for reviewing!

**Pull request merged**
